<?php

$labels['changepassword']  = 'Passwort ändern';
$labels['newpassword']  = 'neues Passwort:';
$labels['confirmpassword']  = 'neues Passwort wiederholen:';
$labels['infotext'] = 'Um Ihr Passwort zu ändern, füllen Sie das nachfolgende Formular aus. Bitte verwenden Sie ein <i>starkes</i> Passwort welches aus Groß- und Kleinbuchstaben, Zahlen und Sonderzeichen besteht.';

$messages['nopassword'] = 'Bitte geben Sie Ihr neues Passwort ein.';
$messages['passwordsdonotmatch'] = 'Die Passwörter stimmen nicht überein. Probieren Sie erneut.';
$messages['passwordvalidation'] = 'Das Passwort muss aus mindestens 10 Zeichen bestehen. Es sollte aus Nummern, Groß- und Kleinschreibung sowie Sonderzeichen bestehen.';
$messages['internalerror'] = 'Verbindungsfehler: Das Passwoert kann nicht gespeichert werden.';
$messages['noapiset'] = 'Die API - Daten fehlen. - Das Passwort kann nicht gespeichert werden.';
$messages['saved'] = 'Das Passwort wurde erfolgreich geändert.';
