<?php

$labels['changepassword']  = 'Change password';
$labels['newpassword']  = 'New Password:';
$labels['confirmpassword']  = 'Confirm Password:';
$labels['infotext'] = 'To change your password, fill out the form below. Use a <i>strong</i> password which includes at least one upper case, one lower case, one number, and one special character.';

$messages['nopassword'] = 'Please input new password.';
$messages['passwordsdonotmatch'] = 'Passwords do not match, please try again.';
$messages['passwordvalidation'] = 'Password must be at least 10 characters long and contain at least one of the following: numbers, lower and upper case letters, special characters';
$messages['internalerror'] = 'Could not save new password. Connection error.';
$messages['noapiset'] = 'Cannot change password. Missing API details.';
$messages['saved'] = 'Password has been changed successfully.';