<?php

$labels['changepassword']  = 'Cambiar contraseña';
$labels['newpassword']  = 'Nueva contraseña:';
$labels['confirmpassword']  = 'Confirmar contraseña:';
$labels['infotext'] = 'Para cambiar su contraseña, complete el formulario de abajo. Utilice una contraseña <i>fuerte</i> que incluya al menos una letra mayúscula, una minúscula, un número y un caracter especial.';

$messages['nopassword'] = 'Por favor, ingrese su nueva contraseña.';
$messages['passwordsdonotmatch'] = 'Las contraseñas no coinciden.';
$messages['passwordvalidation'] = 'La contraseña debe tener al menos 10 caracteres y contener por lo menos uno de cada uno de estos elementos: números, letras mayúsculas y minúsculas, caracteres especiales.';
$messages['internalerror'] = 'No fué posible guardar la nueva contraseña. Error de conexión.';
$messages['noapiset'] = 'No fué posible cambiar la contraseña. Detalles de la API no configurados.';
$messages['saved'] = 'La contraseña ha sido cambiada exitosamente.';
